spring:
  application:
    name: flash-sale

  r2dbc:
    url: r2dbc:mysql://localhost:3306/flash_sale
    username: root
    password: root
    pool:
      initial-size: 10
      max-size: 50

  sql:
    init:
      mode: always

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "flash-sale-order-group"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      listener:
        ack-mode: manual_immediate

external:
  api:
    order:
      url: http://localhost:8082/api/v1/orders
