spring:
  application:
    name: flash-sale

  r2dbc:
    url: r2dbc:mysql://localhost:3306/flash_sale
    username: root
    password: root
    pool:
      initial-size: 10
      max-size: 50

  sql:
    init:
      mode: always

  kafka:
    bootstrap-servers: localhost:9092
